int sensor = A0;
int value;
int count = 0;
int rpm;
int velocity;
int first_digit;
int second_digit;
int pinA = 2;
int pinB = 3;
int pinC = 4;
int pinD = 5;
int pinE = 6;
int pinF = 7;
int pinG = 8;
int D1 = 9;
int D2 = 10;
int D3 = 11;
int D4 = 12;
void setup() {
  pinMode(sensor, INPUT);
  pinMode(pinA, OUTPUT);     
  pinMode(pinB, OUTPUT);     
  pinMode(pinC, OUTPUT);     
  pinMode(pinD, OUTPUT);     
  pinMode(pinE, OUTPUT);     
  pinMode(pinF, OUTPUT);     
  pinMode(pinG, OUTPUT);   
  pinMode(D1, OUTPUT);  
  pinMode(D2, OUTPUT);  
  pinMode(D3, OUTPUT);  
  pinMode(D4, OUTPUT);
  Serial.begin(9600);

}

void loop() {
  count = 0;
  for (int pause = 0;pause <= 20;pause +=1){
    value = analogRead(sensor);
    Serial.println(value);
    if (value <= 100) {
      count ++; 
    }
    delay(75);
  }
  rpm = count*40;
  velocity = ((0.2*rpm)/60)*3.6; // 0.2 is the circumfrence of the tyre in meters. 1.92 multiplied by the rpm gives the speed in meters per minute. Dividing this by 60 gives the speed in meters per second, and finally multiplying this by 3.6 gives the speed in kilometers per hour. 
  Serial.print("The speed is:"); 
  Serial.println(velocity);
  first_digit = velocity / 10;
  second_digit = velocity - (first_digit * 10);
  for (int i = 1;i <= 1000;i++){
    
  switch (first_digit) 
  {
    case 0:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, LOW);
              break;
    case 1:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, LOW);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, LOW);
              break;
    case 2:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, LOW);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, HIGH);
              break;              
    case 3:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, HIGH);
              break;
    case 4:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, LOW);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;                  
    case 5:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, LOW);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
    case 6:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, LOW);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
    case 7:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, LOW);
              break;
    case 8:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
    case 9:   digitalWrite(D1, LOW);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
}              
 delay (1);
   switch (second_digit) 
  {
    case 0:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, LOW);
              break;
    case 1:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, LOW);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, LOW);
              break;
    case 2:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, LOW);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, HIGH);
              break;              
    case 3:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, HIGH);
              break;
    case 4:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, LOW);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;                  
    case 5:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, LOW);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
    case 6:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, LOW);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
    case 7:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, LOW);
              break;
    case 8:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, HIGH);   
              digitalWrite(pinE, HIGH);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
    case 9:   digitalWrite(D1, HIGH);
              digitalWrite(D2, LOW);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, HIGH);   
              digitalWrite(pinB, HIGH);   
              digitalWrite(pinC, HIGH);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, HIGH);   
              digitalWrite(pinG, HIGH);
              break;
}
delay(1);
}
              digitalWrite(D1, HIGH);
              digitalWrite(D2, HIGH);
              digitalWrite(D3, HIGH);
              digitalWrite(D4, HIGH); 
              digitalWrite(pinA, LOW);   
              digitalWrite(pinB, LOW);   
              digitalWrite(pinC, LOW);   
              digitalWrite(pinD, LOW);   
              digitalWrite(pinE, LOW);   
              digitalWrite(pinF, LOW);   
              digitalWrite(pinG, LOW);
                                                                  
}


